// Autogenerated by build_apps_icons.js - E-commerce Store & Apps Icons
import * as React from "react";

export type AppIconCategoryType =
  | "All"
  | "Shipping & Delivery"
  | "Returns & Guarantees"
  | "Security & Trust"
  | "Payments & Checkout"
  | "Customer Support"
  | "Quality & Authenticity"
  | "Eco-Friendly & Ethics"
  | "Promotions & Perks";

export type AppIconItemType = {
  id: string;
  title: string;
  category: AppIconCategoryType;
  description: string;
  keywords: string[];
  placements: string[];
  viewBox?: string;
  elements: string[];
};

export const APP_ICON_CATEGORIES: AppIconCategoryType[] = [
  "All",
  "Shipping & Delivery",
  "Returns & Guarantees",
  "Security & Trust",
  "Payments & Checkout",
  "Customer Support",
  "Quality & Authenticity",
  "Eco-Friendly & Ethics",
  "Promotions & Perks"
];

export const APP_ICONS_DATA: AppIconItemType[] = [
  {
    "id": "free-shipping",
    "title": "Free Shipping",
    "category": "Shipping & Delivery",
    "description": "Delivery truck with cargo checkmark badge indicating free delivery on all eligible orders.",
    "keywords": [
      "shipping",
      "free",
      "truck",
      "delivery",
      "order",
      "parcel",
      "transport",
      "freight",
      "express"
    ],
    "placements": [
      "Product page below Add to Cart",
      "Announcement bar",
      "Cart drawer footer",
      "Checkout footer"
    ],
    "elements": [
      "<rect x=\"1\" y=\"3\" width=\"15\" height=\"13\" rx=\"2\" />",
      "<polygon points=\"16 8 20 8 23 11 23 16 16 16 16 8\" />",
      "<circle cx=\"5.5\" cy=\"18.5\" r=\"2.5\" />",
      "<circle cx=\"18.5\" cy=\"18.5\" r=\"2.5\" />",
      "<path d=\"m5 9.5 2 2 4-4\" />"
    ]
  },
  {
    "id": "fast-delivery",
    "title": "Fast Delivery",
    "category": "Shipping & Delivery",
    "description": "Speeding delivery truck with motion wind trails denoting expedited order fulfillment.",
    "keywords": [
      "fast",
      "delivery",
      "speed",
      "quick",
      "express",
      "rush",
      "same day",
      "haste"
    ],
    "placements": [
      "Product page shipping estimate",
      "Cart drawer",
      "Store announcement banner"
    ],
    "elements": [
      "<path d=\"M13 16V6a2 2 0 0 0-2-2H7\" />",
      "<path d=\"M13 8h4.5l3.5 3.5V16h-2\" />",
      "<circle cx=\"6.5\" cy=\"17.5\" r=\"2.5\" />",
      "<circle cx=\"16.5\" cy=\"17.5\" r=\"2.5\" />",
      "<path d=\"M2 5h3\" />",
      "<path d=\"M1 9h5\" />",
      "<path d=\"M2 13h2\" />",
      "<path d=\"M9 16h5\" />"
    ]
  },
  {
    "id": "express-shipping",
    "title": "Express Air Shipping",
    "category": "Shipping & Delivery",
    "description": "Air freight airplane with parcel package indicating priority overnight or 2-day delivery.",
    "keywords": [
      "express",
      "air",
      "plane",
      "priority",
      "overnight",
      "flight",
      "airplane",
      "rapid"
    ],
    "placements": [
      "Shipping method selector",
      "Product page",
      "Checkout express options"
    ],
    "elements": [
      "<path d=\"M17.8 19.2 16 11l3.5-3.5a2.12 2.12 0 0 0-3-3L13 8 4.8 6.2a1 1 0 0 0-1.1.4l-.5.7 6.3 4.5-3.2 3.2-2.1-.5-.8.5 2.2 2.2 2.2 2.2.5-.8-.5-2.1 3.2-3.2 4.5 6.3.7-.5a1 1 0 0 0 .4-1.1Z\" />"
    ]
  },
  {
    "id": "worldwide-shipping",
    "title": "Worldwide Shipping",
    "category": "Shipping & Delivery",
    "description": "Global earth sphere with shipping parallels representing global international dispatch.",
    "keywords": [
      "global",
      "worldwide",
      "international",
      "globe",
      "earth",
      "export",
      "world",
      "cross border"
    ],
    "placements": [
      "Store header top bar",
      "Footer",
      "Shipping policy banner"
    ],
    "elements": [
      "<circle cx=\"12\" cy=\"12\" r=\"9\" />",
      "<path d=\"M3.6 9h16.8\" />",
      "<path d=\"M3.6 15h16.8\" />",
      "<path d=\"M12 3a15.3 15.3 0 0 1 4 9 15.3 15.3 0 0 1-4 9 15.3 15.3 0 0 1-4-9 15.3 15.3 0 0 1 4-9Z\" />"
    ]
  },
  {
    "id": "local-pickup",
    "title": "Local Store Pickup",
    "category": "Shipping & Delivery",
    "description": "Storefront building with retail entrance for click & collect or curbside pickup.",
    "keywords": [
      "pickup",
      "local",
      "store",
      "curbside",
      "click and collect",
      "retail",
      "shop"
    ],
    "placements": [
      "Cart drawer delivery toggle",
      "Checkout fulfillment choices",
      "Header"
    ],
    "elements": [
      "<path d=\"m2 7 2-4h16l2 4\" />",
      "<path d=\"M4 7v13a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V7\" />",
      "<path d=\"M9 21v-7a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v7\" />",
      "<path d=\"M2 7h20\" />",
      "<circle cx=\"12\" cy=\"10\" r=\"1.5\" />"
    ]
  },
  {
    "id": "order-tracking",
    "title": "Real-Time Tracking",
    "category": "Shipping & Delivery",
    "description": "Map pinpoint with tracking beacon for transparent step-by-step order milestones.",
    "keywords": [
      "tracking",
      "order",
      "gps",
      "status",
      "shipment",
      "locate",
      "pin",
      "map",
      "carrier"
    ],
    "placements": [
      "Order confirmation page",
      "Customer account dashboard",
      "Footer navigation"
    ],
    "elements": [
      "<path d=\"M12 21c-4-4.5-7-8.5-7-12a7 7 0 0 1 14 0c0 3.5-3 7.5-7 12Z\" />",
      "<circle cx=\"12\" cy=\"9\" r=\"2.5\" />",
      "<path d=\"M2 13a10 10 0 0 0 3.5 4.5\" />",
      "<path d=\"M22 13a10 10 0 0 1-3.5 4.5\" />"
    ]
  },
  {
    "id": "safe-packaging",
    "title": "Safe Fragile Packaging",
    "category": "Shipping & Delivery",
    "description": "Carefully sealed carton box protected against impact, moisture, and rough transit.",
    "keywords": [
      "package",
      "packaging",
      "box",
      "safe",
      "fragile",
      "protection",
      "cushioned",
      "care"
    ],
    "placements": [
      "Product page specifications",
      "Cart drawer trust badge"
    ],
    "elements": [
      "<path d=\"M16.5 9.4 7.55 4.24a1.8 1.8 0 0 0-1.8 0L3.5 5.54a1.8 1.8 0 0 0-.9 1.56v5.8a1.8 1.8 0 0 0 .9 1.56l2.25 1.3\" />",
      "<path d=\"M3.29 7 12 12l8.71-5\" />",
      "<path d=\"M12 22V12\" />",
      "<path d=\"M12 22l8.71-5c.8-.46 1.29-1.32 1.29-2.24V8.96a2.6 2.6 0 0 0-1.3-2.26L12 2\" />"
    ]
  },
  {
    "id": "same-day-delivery",
    "title": "Same-Day Dispatch",
    "category": "Shipping & Delivery",
    "description": "Stopwatch with speed markers guaranteeing orders leave the fulfillment center today.",
    "keywords": [
      "same day",
      "today",
      "instant",
      "stopwatch",
      "dispatch",
      "fast",
      "clock",
      "timer"
    ],
    "placements": [
      "Product page buy box countdown",
      "Announcement bar"
    ],
    "elements": [
      "<circle cx=\"12\" cy=\"13\" r=\"8\" />",
      "<path d=\"M12 9v4l2.5 2.5\" />",
      "<path d=\"M10 2h4\" />",
      "<path d=\"M12 2v3\" />",
      "<path d=\"m19 5 1.5 1.5\" />"
    ]
  },
  {
    "id": "contactless-delivery",
    "title": "Contactless Delivery",
    "category": "Shipping & Delivery",
    "description": "Safe doorstep drop-off package with contactless wireless signal indicator.",
    "keywords": [
      "contactless",
      "doorstep",
      "safe",
      "hygiene",
      "delivery",
      "no contact",
      "drop off"
    ],
    "placements": [
      "Checkout delivery preferences",
      "Shipping FAQ modal"
    ],
    "elements": [
      "<path d=\"M4 10h16v10a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V10Z\" />",
      "<path d=\"m4 10 3-6h10l3 6\" />",
      "<path d=\"M12 10v12\" />",
      "<path d=\"M8 2a5 5 0 0 1 8 0\" />",
      "<path d=\"M10 4.5a2.5 2.5 0 0 1 4 0\" />"
    ]
  },
  {
    "id": "easy-returns",
    "title": "Easy Returns",
    "category": "Returns & Guarantees",
    "description": "Circular return loop with package symbolizing straightforward, stress-free return policies.",
    "keywords": [
      "return",
      "refund",
      "exchange",
      "loop",
      "easy",
      "policy",
      "send back",
      "hassle free"
    ],
    "placements": [
      "Product page trust block",
      "Cart drawer",
      "Footer",
      "Checkout sidebar"
    ],
    "elements": [
      "<path d=\"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8\" />",
      "<path d=\"M3 3v5h5\" />",
      "<path d=\"m10 15 2-3 2 3\" />",
      "<path d=\"M12 12v-3\" />"
    ]
  },
  {
    "id": "money-back-guarantee",
    "title": "Money-Back Guarantee",
    "category": "Returns & Guarantees",
    "description": "Official guarantee rosette with currency symbol assuring a complete refund if unsatisfied.",
    "keywords": [
      "money back",
      "guarantee",
      "refund",
      "cash",
      "satisfaction",
      "risk free",
      "dollar"
    ],
    "placements": [
      "Product page buy box",
      "Pricing block",
      "Checkout sidebar"
    ],
    "elements": [
      "<circle cx=\"12\" cy=\"12\" r=\"9\" />",
      "<path d=\"M14.5 9h-3.5a1.5 1.5 0 0 0 0 3h2a1.5 1.5 0 0 1 0 3H9\" />",
      "<path d=\"M12 7v10\" />",
      "<path d=\"m8 19-3 3v-5\" />",
      "<path d=\"m16 19 3 3v-5\" />"
    ]
  },
  {
    "id": "30-day-returns",
    "title": "30-Day Free Returns",
    "category": "Returns & Guarantees",
    "description": "Calendar tile with '30' days marking an extended risk-free trial window.",
    "keywords": [
      "30 day",
      "return window",
      "calendar",
      "trial",
      "guarantee",
      "month",
      "risk free"
    ],
    "placements": [
      "Product page trust row",
      "Cart drawer summary",
      "Footer policy"
    ],
    "elements": [
      "<rect x=\"3\" y=\"4\" width=\"18\" height=\"17\" rx=\"2\" />",
      "<path d=\"M16 2v4\" />",
      "<path d=\"M8 2v4\" />",
      "<path d=\"M3 9h18\" />",
      "<path d=\"M7 13h2a1 1 0 0 1 1 1v0a1 1 0 0 1-1 1H7v2h3\" />",
      "<path d=\"M14 13h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-2a1 1 0 0 1 1-1Z\" />"
    ]
  },
  {
    "id": "hassle-free-exchange",
    "title": "Hassle-Free Exchange",
    "category": "Returns & Guarantees",
    "description": "Bidirectional circular exchange arrows for effortless sizing or color substitutions.",
    "keywords": [
      "exchange",
      "swap",
      "replace",
      "size",
      "switch",
      "arrows",
      "trade"
    ],
    "placements": [
      "Product page apparel size guide",
      "Customer return center"
    ],
    "elements": [
      "<path d=\"m4 8 3-3 3 3\" />",
      "<path d=\"M7 5v9a3 3 0 0 0 3 3h7\" />",
      "<path d=\"m20 16-3 3-3-3\" />",
      "<path d=\"M17 19v-9a3 3 0 0 0-3-3H7\" />"
    ]
  },
  {
    "id": "instant-refund",
    "title": "Instant Refund",
    "category": "Returns & Guarantees",
    "description": "Lightning bolt with wallet signifying quick automated refunds with no delays.",
    "keywords": [
      "instant",
      "refund",
      "reimburse",
      "lightning",
      "fast money",
      "credit",
      "payout"
    ],
    "placements": [
      "Checkout trust badge",
      "Return policy modal"
    ],
    "elements": [
      "<path d=\"M20 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2Z\" />",
      "<path d=\"M2 11h20\" />",
      "<path d=\"m13 5-3 5h4l-2 5\" />"
    ]
  },
  {
    "id": "lifetime-warranty",
    "title": "Lifetime Warranty",
    "category": "Returns & Guarantees",
    "description": "Security shield with infinity ribbon symbol promising lifetime repair or replacement.",
    "keywords": [
      "lifetime",
      "warranty",
      "infinity",
      "coverage",
      "durable",
      "guaranteed",
      "forever"
    ],
    "placements": [
      "Product page specifications",
      "Trust badge strip",
      "About us"
    ],
    "elements": [
      "<path d=\"M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z\" />",
      "<path d=\"M8.5 12c-1.5-1.5-3 0-1.5 1.5s3 0 1.5-1.5c1.5-1.5 3 0 1.5 1.5s-3 0-1.5-1.5Z\" />",
      "<circle cx=\"9\" cy=\"12\" r=\"1.5\" />",
      "<circle cx=\"15\" cy=\"12\" r=\"1.5\" />",
      "<path d=\"M10.2 12.8 13.8 11.2\" />",
      "<path d=\"M10.2 11.2 13.8 12.8\" />"
    ]
  },
  {
    "id": "secure-checkout",
    "title": "Secure Checkout",
    "category": "Security & Trust",
    "description": "Shopping cart protected with a security padlock assuring total checkout safety.",
    "keywords": [
      "secure",
      "checkout",
      "cart",
      "lock",
      "safety",
      "trust",
      "payment",
      "encryption"
    ],
    "placements": [
      "Cart checkout button",
      "Checkout header",
      "Product buy box"
    ],
    "elements": [
      "<circle cx=\"8\" cy=\"21\" r=\"1.5\" />",
      "<circle cx=\"17\" cy=\"21\" r=\"1.5\" />",
      "<path d=\"M2 3h3l2.4 11.2a1.5 1.5 0 0 0 1.5 1.2h8.6a1.5 1.5 0 0 0 1.5-1.2L21 7H7\" />",
      "<rect x=\"11\" y=\"9\" width=\"6\" height=\"5\" rx=\"1\" />",
      "<path d=\"M12.5 9V7.5a1.5 1.5 0 0 1 3 0V9\" />"
    ]
  },
  {
    "id": "ssl-encryption",
    "title": "256-Bit SSL Encryption",
    "category": "Security & Trust",
    "description": "Heavy shield with padlock representing bank-standard cryptographic data protection.",
    "keywords": [
      "ssl",
      "encryption",
      "256 bit",
      "https",
      "crypto",
      "safe",
      "lock",
      "tls"
    ],
    "placements": [
      "Checkout footer",
      "Cart drawer footer",
      "Website footer security badges"
    ],
    "elements": [
      "<path d=\"M12 2 4 5.5v6c0 5.5 3.8 10.7 8 12 4.2-1.3 8-6.5 8-12v-6L12 2Z\" />",
      "<rect x=\"9.5\" y=\"11\" width=\"5\" height=\"4\" rx=\"1\" />",
      "<path d=\"M10.5 11V9.5a1.5 1.5 0 0 1 3 0V11\" />",
      "<circle cx=\"12\" cy=\"13\" r=\".5\" />"
    ]
  },
  {
    "id": "privacy-protected",
    "title": "Privacy Protected / GDPR",
    "category": "Security & Trust",
    "description": "Shield with private eye safeguard promising personal customer data is never sold or shared.",
    "keywords": [
      "privacy",
      "gdpr",
      "private",
      "data",
      "confidential",
      "security",
      "safe",
      "shield"
    ],
    "placements": [
      "Email signup popup",
      "Checkout customer info step",
      "Footer"
    ],
    "elements": [
      "<path d=\"M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z\" />",
      "<path d=\"M9 12a3 3 0 0 1 5.2-2\" />",
      "<path d=\"M15 12a3 3 0 0 1-5.2 2\" />",
      "<circle cx=\"12\" cy=\"12\" r=\"1\" />",
      "<path d=\"m4 4 16 16\" />"
    ]
  },
  {
    "id": "buyer-protection",
    "title": "Buyer Protection",
    "category": "Security & Trust",
    "description": "Protective shield enveloping a shopping bag with guaranteed order resolution.",
    "keywords": [
      "buyer protection",
      "guarantee",
      "umbrella",
      "escrow",
      "safe buy",
      "verified",
      "bag"
    ],
    "placements": [
      "Product page trust strip",
      "Cart drawer",
      "Checkout summary"
    ],
    "elements": [
      "<path d=\"M12 2 3 6v6c0 5.5 3.8 10.7 9 12 5.2-1.3 9-6.5 9-12V6l-9-4Z\" />",
      "<path d=\"M9 11h6a1 1 0 0 1 1 1v4a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2v-4a1 1 0 0 1 1-1Z\" />",
      "<path d=\"M10 11V9a2 2 0 0 1 4 0v2\" />"
    ]
  },
  {
    "id": "verified-merchant",
    "title": "Verified Merchant",
    "category": "Security & Trust",
    "description": "Shopify-style verified merchant seal with checkmark verifying certified store identity.",
    "keywords": [
      "verified",
      "merchant",
      "authentic",
      "official",
      "check",
      "seal",
      "badge",
      "certified"
    ],
    "placements": [
      "Store header",
      "Footer",
      "Product page",
      "About us page"
    ],
    "elements": [
      "<path d=\"M12 2l2.4 2.1 3.2-.3 1.2 3 2.9 1.4-.7 3.1 1.9 2.6-2.1 2.4.3 3.2-3 1.2-1.4 2.9-3.1-.7-2.6 1.9-2.4-2.1-3.2.3-1.2-3-2.9-1.4.7-3.1-1.9-2.6 2.1-2.4-.3-3.2 3-1.2 1.4-2.9 3.1.7L12 2Z\" />",
      "<path d=\"m8.5 12 2.5 2.5 5-5\" />"
    ]
  },
  {
    "id": "fraud-prevention",
    "title": "Fraud Prevention",
    "category": "Security & Trust",
    "description": "Radar security shield scanning and blocking unauthorized fraudulent activity.",
    "keywords": [
      "fraud",
      "anti-fraud",
      "radar",
      "shield",
      "scam protection",
      "secure",
      "scan"
    ],
    "placements": [
      "Checkout trust badge",
      "Payment page disclaimer"
    ],
    "elements": [
      "<path d=\"M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z\" />",
      "<path d=\"M12 8a4 4 0 0 1 4 4\" />",
      "<path d=\"M12 6a6 6 0 0 1 6 6\" />",
      "<circle cx=\"12\" cy=\"12\" r=\"1.5\" />",
      "<path d=\"M12 12 8.5 8.5\" />"
    ]
  },
  {
    "id": "anti-counterfeit",
    "title": "100% Authentic Guarantee",
    "category": "Security & Trust",
    "description": "Official stamp certification ensuring genuine merchandise straight from authorized makers.",
    "keywords": [
      "authentic",
      "genuine",
      "original",
      "anti counterfeit",
      "stamp",
      "certified",
      "real"
    ],
    "placements": [
      "Product page badges",
      "Brand authenticity policy"
    ],
    "elements": [
      "<circle cx=\"12\" cy=\"12\" r=\"9\" />",
      "<circle cx=\"12\" cy=\"12\" r=\"6\" stroke-dasharray=\"3 3\" />",
      "<path d=\"m9 12 2 2 4-4\" />"
    ]
  },
  {
    "id": "credit-card-secure",
    "title": "Secure Card Payments",
    "category": "Payments & Checkout",
    "description": "Credit card with EMV smart chip and magnetic stripe for secure Visa/Mastercard processing.",
    "keywords": [
      "credit card",
      "visa",
      "mastercard",
      "amex",
      "chip",
      "debit",
      "payments",
      "cards"
    ],
    "placements": [
      "Cart drawer",
      "Product page payment icons",
      "Footer payment list"
    ],
    "elements": [
      "<rect x=\"2\" y=\"5\" width=\"20\" height=\"14\" rx=\"2\" />",
      "<path d=\"M2 10h20\" />",
      "<rect x=\"5\" y=\"13\" width=\"4\" height=\"3\" rx=\".5\" />",
      "<path d=\"M15 14.5h3\" />"
    ]
  },
  {
    "id": "cash-on-delivery",
    "title": "Cash on Delivery (COD)",
    "category": "Payments & Checkout",
    "description": "Currency banknotes with delivery package for customers paying physical cash on arrival.",
    "keywords": [
      "cod",
      "cash on delivery",
      "cash",
      "banknotes",
      "pay on arrival",
      "delivery",
      "money"
    ],
    "placements": [
      "Shipping options",
      "Checkout payment methods",
      "Product page badge"
    ],
    "elements": [
      "<rect x=\"2\" y=\"6\" width=\"16\" height=\"10\" rx=\"2\" />",
      "<circle cx=\"10\" cy=\"11\" r=\"2\" />",
      "<path d=\"M6 18h14a2 2 0 0 0 2-2V8\" />",
      "<path d=\"M18 14h4\" />"
    ]
  },
  {
    "id": "flexible-installments",
    "title": "Buy Now, Pay Later (BNPL)",
    "category": "Payments & Checkout",
    "description": "Split payment card slices for 4 interest-free installments (Klarna, Afterpay, Shop Pay).",
    "keywords": [
      "bnpl",
      "installments",
      "klarna",
      "afterpay",
      "split pay",
      "pay in 4",
      "affirm",
      "shop pay"
    ],
    "placements": [
      "Product price breakdown",
      "Cart drawer",
      "Checkout"
    ],
    "elements": [
      "<rect x=\"3\" y=\"4\" width=\"18\" height=\"16\" rx=\"2\" />",
      "<path d=\"M3 10h18\" />",
      "<path d=\"M8 10v10\" />",
      "<path d=\"M12 10v10\" />",
      "<path d=\"M16 10v10\" />",
      "<path d=\"M8 2v3\" />",
      "<path d=\"M16 2v3\" />"
    ]
  },
  {
    "id": "zero-fees",
    "title": "No Hidden Fees / 0% Interest",
    "category": "Payments & Checkout",
    "description": "Discount tag with zero percent sign indicating 100% upfront transparent pricing.",
    "keywords": [
      "zero fees",
      "no hidden fees",
      "0 percent",
      "transparent",
      "discount",
      "tax included",
      "pricing"
    ],
    "placements": [
      "Product page price block",
      "Cart summary",
      "Checkout"
    ],
    "elements": [
      "<path d=\"M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82Z\" />",
      "<circle cx=\"7\" cy=\"7\" r=\"1.5\" />",
      "<path d=\"m9 15 4-4\" />",
      "<circle cx=\"9.5\" cy=\"11.5\" r=\".75\" />",
      "<circle cx=\"12.5\" cy=\"14.5\" r=\".75\" />"
    ]
  },
  {
    "id": "wallet-pay",
    "title": "Apple & Google Pay / NFC",
    "category": "Payments & Checkout",
    "description": "Smartphone radiating contactless NFC waves for one-tap express mobile checkout.",
    "keywords": [
      "wallet",
      "apple pay",
      "google pay",
      "nfc",
      "phone",
      "contactless",
      "tap to pay",
      "mobile"
    ],
    "placements": [
      "Express checkout buttons",
      "Cart drawer footer",
      "Product page"
    ],
    "elements": [
      "<rect x=\"6\" y=\"2\" width=\"12\" height=\"20\" rx=\"2.5\" />",
      "<path d=\"M10 5h4\" />",
      "<circle cx=\"12\" cy=\"18\" r=\"1\" />",
      "<path d=\"M21 9a4 4 0 0 1 0 6\" />",
      "<path d=\"M23 7a7 7 0 0 1 0 10\" />"
    ]
  },
  {
    "id": "crypto-accepted",
    "title": "Crypto Payments Accepted",
    "category": "Payments & Checkout",
    "description": "Digital blockchain cryptocurrency token for Web3 and decentralized checkout.",
    "keywords": [
      "crypto",
      "bitcoin",
      "ethereum",
      "usdt",
      "blockchain",
      "digital currency",
      "web3",
      "coin"
    ],
    "placements": [
      "Footer payment icons",
      "Cart checkout methods"
    ],
    "elements": [
      "<circle cx=\"12\" cy=\"12\" r=\"9\" />",
      "<path d=\"M9 8h4.5a2.5 2.5 0 0 1 0 5H9\" />",
      "<path d=\"M9 13h5.5a2.5 2.5 0 0 1 0 5H9\" />",
      "<path d=\"M9 6v14\" />",
      "<path d=\"M12 6v2\" />",
      "<path d=\"M12 18v2\" />",
      "<path d=\"M14 6v2\" />",
      "<path d=\"M14 18v2\" />"
    ]
  },
  {
    "id": "support-24-7",
    "title": "24/7 Customer Support",
    "category": "Customer Support",
    "description": "Support headset with 24/7 indicator ensuring round-the-clock merchant help.",
    "keywords": [
      "support",
      "24/7",
      "headset",
      "help",
      "customer service",
      "agent",
      "call center",
      "assist"
    ],
    "placements": [
      "Store header",
      "Product page trust block",
      "Footer",
      "Contact page"
    ],
    "elements": [
      "<path d=\"M3 14h2a2 2 0 0 0 2-2V9a6 6 0 0 1 12 0v3a2 2 0 0 0 2 2h2\" />",
      "<path d=\"M21 14v4a2 2 0 0 1-2 2h-4\" />",
      "<path d=\"M15 20h.01\" />",
      "<rect x=\"2\" y=\"13\" width=\"3\" height=\"5\" rx=\"1\" />",
      "<rect x=\"19\" y=\"13\" width=\"3\" height=\"5\" rx=\"1\" />",
      "<path d=\"M10 7.5h1.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H10v1.5h2\" />",
      "<path d=\"M13.5 11h1.5v-3.5l-1.5 2.5\" />"
    ]
  },
  {
    "id": "live-chat",
    "title": "Live Chat Support",
    "category": "Customer Support",
    "description": "Interactive chat speech bubble with typing indicators for instantaneous responses.",
    "keywords": [
      "chat",
      "live chat",
      "messaging",
      "bubbles",
      "instant reply",
      "help",
      "talk",
      "agent"
    ],
    "placements": [
      "Floating chat widget",
      "Header",
      "FAQ section",
      "Product page"
    ],
    "elements": [
      "<path d=\"M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z\" />",
      "<circle cx=\"8.5\" cy=\"10\" r=\"1\" />",
      "<circle cx=\"12\" cy=\"10\" r=\"1\" />",
      "<circle cx=\"15.5\" cy=\"10\" r=\"1\" />"
    ]
  },
  {
    "id": "phone-assistance",
    "title": "Toll-Free Phone Support",
    "category": "Customer Support",
    "description": "Telephone receiver with signal broadcast waves for direct spoken telephone support.",
    "keywords": [
      "phone",
      "call",
      "toll free",
      "telephone",
      "hotline",
      "assistance",
      "talk",
      "ring"
    ],
    "placements": [
      "Header top bar",
      "Contact page",
      "Footer"
    ],
    "elements": [
      "<path d=\"M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z\" />",
      "<path d=\"M14 2a8 8 0 0 1 8 8\" />",
      "<path d=\"M14 6a4 4 0 0 1 4 4\" />"
    ]
  },
  {
    "id": "email-support",
    "title": "Fast Email Assistance",
    "category": "Customer Support",
    "description": "Postal envelope with lightning wing signifying rapid under-1-hour email tickets.",
    "keywords": [
      "email",
      "inbox",
      "mail",
      "contact",
      "fast response",
      "ticket",
      "support",
      "letter"
    ],
    "placements": [
      "Contact form",
      "Footer",
      "Help center page"
    ],
    "elements": [
      "<rect x=\"2\" y=\"4\" width=\"20\" height=\"16\" rx=\"2\" />",
      "<path d=\"m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7\" />",
      "<path d=\"m11 11-1 3h3l-1 3\" />"
    ]
  },
  {
    "id": "help-center",
    "title": "Knowledge Base / Help Center",
    "category": "Customer Support",
    "description": "Lifebuoy life preserver ring providing self-service answers and troubleshooting guides.",
    "keywords": [
      "help center",
      "lifebuoy",
      "faq",
      "knowledge base",
      "guide",
      "answers",
      "docs"
    ],
    "placements": [
      "Header navigation",
      "Footer links",
      "Customer portal"
    ],
    "elements": [
      "<circle cx=\"12\" cy=\"12\" r=\"9\" />",
      "<circle cx=\"12\" cy=\"12\" r=\"4\" />",
      "<path d=\"m4.93 4.93 3.54 3.54\" />",
      "<path d=\"m15.53 15.53 3.54 3.54\" />",
      "<path d=\"m4.93 19.07 3.54-3.54\" />",
      "<path d=\"m15.53 8.47 3.54-3.54\" />"
    ]
  },
  {
    "id": "premium-quality",
    "title": "Premium Quality",
    "category": "Quality & Authenticity",
    "description": "Royal crown with sparkles representing superior craftsmanship and top-tier materials.",
    "keywords": [
      "premium",
      "quality",
      "crown",
      "luxury",
      "craftsmanship",
      "high end",
      "gold",
      "best"
    ],
    "placements": [
      "Product page feature highlights",
      "Brand story banner",
      "Collection header"
    ],
    "elements": [
      "<path d=\"M3 18h18v2H3z\" />",
      "<path d=\"M4 18 2 7l6 4 4-6 4 6 6-4-2 11H4z\" />",
      "<circle cx=\"12\" cy=\"4\" r=\"1\" />",
      "<circle cx=\"2\" cy=\"7\" r=\"1\" />",
      "<circle cx=\"22\" cy=\"7\" r=\"1\" />",
      "<circle cx=\"8\" cy=\"11\" r=\"1\" />",
      "<circle cx=\"16\" cy=\"11\" r=\"1\" />"
    ]
  },
  {
    "id": "five-star-rating",
    "title": "5-Star Rated Product",
    "category": "Quality & Authenticity",
    "description": "Lustrous five-point star with celebration pedestal reflecting top customer ratings.",
    "keywords": [
      "5 star",
      "rating",
      "reviews",
      "stars",
      "top rated",
      "customer feedback",
      "score"
    ],
    "placements": [
      "Product page review summary",
      "Hero banner",
      "Social proof bar"
    ],
    "elements": [
      "<path d=\"M12 2l2.4 5 5.5.8-4 3.9 1 5.5-4.9-2.6L7.1 17.2l1-5.5-4-3.9 5.5-.8L12 2z\" />",
      "<path d=\"M3 19l2 3h14l2-3\" />"
    ]
  },
  {
    "id": "award-winning",
    "title": "Award-Winning Products",
    "category": "Quality & Authenticity",
    "description": "Champion trophy cup with celebration handles recognizing industry awards.",
    "keywords": [
      "award",
      "trophy",
      "winner",
      "champion",
      "recognized",
      "best in class",
      "cup"
    ],
    "placements": [
      "Homepage credibility bar",
      "Product awards badge",
      "About us page"
    ],
    "elements": [
      "<path d=\"M6 9H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h2\" />",
      "<path d=\"M18 9h2a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2h-2\" />",
      "<path d=\"M6 3h12v7a6 6 0 0 1-12 0V3z\" />",
      "<path d=\"M12 16v4\" />",
      "<path d=\"M8 20h8\" />"
    ]
  },
  {
    "id": "satisfaction-guaranteed",
    "title": "100% Satisfaction Guaranteed",
    "category": "Quality & Authenticity",
    "description": "Thumbs-up inside a rosette ribbon emblem guaranteeing total customer delight.",
    "keywords": [
      "satisfaction",
      "guaranteed",
      "thumbs up",
      "happy customer",
      "risk free",
      "love it"
    ],
    "placements": [
      "Product page buy box",
      "Cart drawer",
      "Checkout guarantees"
    ],
    "elements": [
      "<circle cx=\"12\" cy=\"12\" r=\"9\" />",
      "<path d=\"M7 11.5V16a1 1 0 0 0 1 1h2\" />",
      "<path d=\"M10 17h4.8a1.5 1.5 0 0 0 1.4-1l1.3-4a1.5 1.5 0 0 0-1.4-2H13V7.5a1.5 1.5 0 0 0-3 0V11l-2.5 1\" />",
      "<path d=\"m8 20-2 2\" />",
      "<path d=\"m16 20 2 2\" />"
    ]
  },
  {
    "id": "handmade-craft",
    "title": "Handmade / Artisanal",
    "category": "Quality & Authenticity",
    "description": "Artisan hands carefully crafting products in small batches with personal dedication.",
    "keywords": [
      "handmade",
      "artisanal",
      "craft",
      "hands",
      "custom made",
      "small batch",
      "artisan"
    ],
    "placements": [
      "Product page materials & origin",
      "Brand bio",
      "Collection footer"
    ],
    "elements": [
      "<path d=\"M18 11V6a2 2 0 0 0-2-2 2 2 0 0 0-2 2v4\" />",
      "<path d=\"M14 10V4a2 2 0 0 0-2-2 2 2 0 0 0-2 2v6\" />",
      "<path d=\"M10 10.5V6a2 2 0 0 0-2-2 2 2 0 0 0-2 2v8\" />",
      "<path d=\"M6 14a6 6 0 0 0 12 0v-3a2 2 0 0 0-2-2\" />"
    ]
  },
  {
    "id": "lab-tested",
    "title": "Lab Tested / Clinically Proven",
    "category": "Quality & Authenticity",
    "description": "Laboratory beaker with verified checkmark denoting third-party purity testing.",
    "keywords": [
      "lab tested",
      "clinical",
      "proven",
      "certified",
      "science",
      "pure",
      "tested",
      "formula"
    ],
    "placements": [
      "Beauty / Supplements product page",
      "Ingredient breakdown",
      "About formulation"
    ],
    "elements": [
      "<path d=\"M9 3h6\" />",
      "<path d=\"M10 3v5l-5 9a2 2 0 0 0 1.7 3h10.6a2 2 0 0 0 1.7-3l-5-9V3\" />",
      "<path d=\"M7.5 15h9\" />",
      "<path d=\"m9.5 12 1.5 1.5 3.5-3.5\" />"
    ]
  },
  {
    "id": "authentic-original",
    "title": "Certified Authentic Seal",
    "category": "Quality & Authenticity",
    "description": "Rosette medal with central checkmark proving licensed, genuine manufacturer provenance.",
    "keywords": [
      "authentic",
      "certified",
      "rosette",
      "ribbon",
      "seal",
      "official",
      "original",
      "genuine"
    ],
    "placements": [
      "Product page header",
      "Brand seal badge",
      "Footer credentials"
    ],
    "elements": [
      "<circle cx=\"12\" cy=\"9\" r=\"6\" />",
      "<path d=\"m9.5 9 1.5 1.5 3.5-3.5\" />",
      "<path d=\"m8 14-3 7 7-3 7 3-3-7\" />"
    ]
  },
  {
    "id": "eco-friendly",
    "title": "Eco-Friendly / Sustainable",
    "category": "Eco-Friendly & Ethics",
    "description": "Circular green leaf renewal cycle safeguarding planet Earth and natural resources.",
    "keywords": [
      "eco",
      "green",
      "sustainable",
      "leaf",
      "planet",
      "environment",
      "earth",
      "nature"
    ],
    "placements": [
      "Product sustainability section",
      "Cart drawer",
      "Store footer pledge"
    ],
    "elements": [
      "<path d=\"M11 20A7 7 0 0 1 4 13C4 8 8 4 13 4c5 0 7 2 7 7a7 7 0 0 1-7 7l-2 2z\" />",
      "<path d=\"M13 4v9a4 4 0 0 1-4 4\" />"
    ]
  },
  {
    "id": "recyclable-100",
    "title": "100% Recyclable Packaging",
    "category": "Eco-Friendly & Ethics",
    "description": "Mobius continuous 3-arrow recycling loop for zero-plastic, circular packaging.",
    "keywords": [
      "recyclable",
      "recycle",
      "zero waste",
      "circular",
      "biodegradable",
      "plastic free",
      "packaging"
    ],
    "placements": [
      "Packaging info modal",
      "Product page footer",
      "Cart eco pledge"
    ],
    "elements": [
      "<path d=\"m7 19-3-5h4l2 3.5\" />",
      "<path d=\"m17 19 3-5h-4l-2 3.5\" />",
      "<path d=\"M12 4 9 9h6l-3-5z\" />",
      "<path d=\"M4 14l3.5-6h2\" />",
      "<path d=\"M20 14l-3.5-6h-2\" />",
      "<path d=\"M8.5 19h7\" />"
    ]
  },
  {
    "id": "cruelty-free",
    "title": "Cruelty-Free / Leaping Bunny",
    "category": "Eco-Friendly & Ethics",
    "description": "Gentle bunny silhouette guaranteeing no testing on animals throughout creation.",
    "keywords": [
      "cruelty free",
      "no animal testing",
      "bunny",
      "rabbit",
      "ethical",
      "compassion",
      "vegan"
    ],
    "placements": [
      "Cosmetics & skincare product pages",
      "Brand ethical values page"
    ],
    "elements": [
      "<path d=\"M12 21a8 8 0 0 1-8-8c0-3.5 2-6 5-6 1.5 0 2.5.5 3 1.5.5-1 1.5-1.5 3-1.5 3 0 5 2.5 5 6a8 8 0 0 1-8 8z\" />",
      "<path d=\"M7 7c-.5-2-1.5-4-3-4-.5 2 .5 4 1.5 5\" />",
      "<path d=\"M17 7c.5-2 1.5-4 3-4 .5 2-.5 4-1.5 5\" />",
      "<circle cx=\"9.5\" cy=\"13.5\" r=\".75\" />",
      "<circle cx=\"14.5\" cy=\"13.5\" r=\".75\" />"
    ]
  },
  {
    "id": "organic-natural",
    "title": "100% Organic & Natural",
    "category": "Eco-Friendly & Ethics",
    "description": "Botanical seedling emerging from fertile ground signifying pesticide-free ingredients.",
    "keywords": [
      "organic",
      "natural",
      "seedling",
      "pure",
      "botanical",
      "chemical free",
      "clean",
      "healthy"
    ],
    "placements": [
      "Food & beverage, wellness, skincare product pages"
    ],
    "elements": [
      "<path d=\"M12 22v-9\" />",
      "<path d=\"M12 13a5 5 0 0 1 5-5c0 5-5 5-5 5z\" />",
      "<path d=\"M12 15a5 5 0 0 0-5-5c0 5 5 5 5 5z\" />",
      "<path d=\"M3 22h18\" />"
    ]
  },
  {
    "id": "carbon-neutral",
    "title": "Carbon Neutral Delivery",
    "category": "Eco-Friendly & Ethics",
    "description": "Atmospheric cloud with balanced leaf denoting 100% carbon-offset freight.",
    "keywords": [
      "carbon neutral",
      "co2",
      "emissions",
      "offset",
      "climate friendly",
      "clean air",
      "footprint"
    ],
    "placements": [
      "Shipping options",
      "Checkout eco badge",
      "Sustainability report"
    ],
    "elements": [
      "<path d=\"M17.5 19H9a5 5 0 0 1-.2-10 6 6 0 0 1 11.2 2 4 4 0 0 1-2.5 8z\" />",
      "<path d=\"M12 11c1.5-2 3-1.5 3 0s-1.5 2-3 0z\" />",
      "<path d=\"M12 11v5\" />"
    ]
  },
  {
    "id": "vegan-certified",
    "title": "Certified Vegan",
    "category": "Eco-Friendly & Ethics",
    "description": "Plant-based leaf forming a certified V insignia for 100% animal-free products.",
    "keywords": [
      "vegan",
      "plant based",
      "dairy free",
      "vegetarian",
      "ethical",
      "cruelty free",
      "clean"
    ],
    "placements": [
      "Product page specifications",
      "Dietary badges",
      "Cart drawer"
    ],
    "elements": [
      "<circle cx=\"12\" cy=\"12\" r=\"9\" />",
      "<path d=\"m8 8 4 9 4-9\" />",
      "<path d=\"M12 17c1-3 3-5 5-5\" />"
    ]
  },
  {
    "id": "free-gift",
    "title": "Free Gift with Purchase",
    "category": "Promotions & Perks",
    "description": "Celebratory gift box wrapped in ribbon bow with surprise bonus sparkles.",
    "keywords": [
      "free gift",
      "bonus",
      "gift box",
      "present",
      "gwp",
      "reward",
      "bundle",
      "surprise"
    ],
    "placements": [
      "Cart progress bar (Spend $X get free gift)",
      "Product page add-on",
      "Checkout"
    ],
    "elements": [
      "<rect x=\"3\" y=\"8\" width=\"18\" height=\"4\" rx=\"1\" />",
      "<rect x=\"4\" y=\"12\" width=\"16\" height=\"9\" rx=\"1\" />",
      "<path d=\"M12 8v13\" />",
      "<path d=\"M12 8H7.5a2.5 2.5 0 0 1 0-5C11 3 12 8 12 8z\" />",
      "<path d=\"M12 8h4.5a2.5 2.5 0 0 0 0-5C13 3 12 8 12 8z\" />"
    ]
  },
  {
    "id": "best-price-guarantee",
    "title": "Best Price Guarantee",
    "category": "Promotions & Perks",
    "description": "Retail tag with handshake agreement promising lowest market price matching.",
    "keywords": [
      "best price",
      "price match",
      "lowest price",
      "guarantee",
      "deal",
      "discount",
      "cheap"
    ],
    "placements": [
      "Product page price block",
      "Comparison table",
      "Cart drawer summary"
    ],
    "elements": [
      "<path d=\"M11 2 2 11l9 9 9-9V2h-9z\" />",
      "<circle cx=\"7\" cy=\"7\" r=\"1.5\" />",
      "<path d=\"M10 13l2-2 2 2\" />",
      "<path d=\"M14 11l-2 2-2-2\" />"
    ]
  },
  {
    "id": "loyalty-rewards",
    "title": "Member Rewards / Points",
    "category": "Promotions & Perks",
    "description": "Faceted diamond gem accumulating loyalty reward points on every transaction.",
    "keywords": [
      "loyalty",
      "rewards",
      "points",
      "gem",
      "diamond",
      "vip",
      "earn points",
      "perks"
    ],
    "placements": [
      "Cart drawer rewards bar",
      "Product page earn X points",
      "Account header"
    ],
    "elements": [
      "<path d=\"M6 3h12l4 6-10 12L2 9l4-6z\" />",
      "<path d=\"M2 9h20\" />",
      "<path d=\"m12 21 4-12\" />",
      "<path d=\"M12 21 8 9\" />",
      "<path d=\"m6 3 6 6 6-6\" />"
    ]
  },
  {
    "id": "vip-member",
    "title": "VIP Exclusive Perk",
    "category": "Promotions & Perks",
    "description": "Golden crown ribbon badge unlocked for top-tier VIP community members.",
    "keywords": [
      "vip",
      "member",
      "exclusive",
      "crown",
      "elite",
      "club",
      "tier",
      "special"
    ],
    "placements": [
      "Customer account status",
      "VIP collection badge",
      "Header"
    ],
    "elements": [
      "<circle cx=\"12\" cy=\"12\" r=\"9\" />",
      "<path d=\"M7 14 5 9l3 2 4-4 4 4 3-2-2 5H7z\" />",
      "<path d=\"M7 15h10\" />"
    ]
  },
  {
    "id": "special-discount",
    "title": "Special Coupon / Promo",
    "category": "Promotions & Perks",
    "description": "Coupon voucher with perforated scissors cutout for promo code discounts.",
    "keywords": [
      "discount",
      "coupon",
      "promo",
      "voucher",
      "deal",
      "sale",
      "percent",
      "save",
      "code"
    ],
    "placements": [
      "Cart discount box",
      "Announcement bar",
      "Exit intent popup"
    ],
    "elements": [
      "<rect x=\"2\" y=\"6\" width=\"20\" height=\"12\" rx=\"2\" />",
      "<path d=\"M14 6v12\" stroke-dasharray=\"2 2\" />",
      "<circle cx=\"8\" cy=\"12\" r=\"2\" />",
      "<path d=\"M2 12a2 2 0 0 0 2-2V8\" />",
      "<path d=\"M22 12a2 2 0 0 1-2-2V8\" />"
    ]
  }
];

export function getIconById(id: string): AppIconItemType | undefined {
  return APP_ICONS_DATA.find((i) => i.id === id);
}

export type AppIconProps = React.SVGProps<SVGSVGElement> & {
  name: string;
  size?: number | string;
  strokeWidth?: number;
  color?: string;
};

/**
 * Universal vector AppIcon component rendering pure inline SVG.
 */
export function AppIcon({
  name,
  size = 24,
  strokeWidth = 1.75,
  color = "currentColor",
  className,
  style,
  ...props
}: AppIconProps) {
  const icon = getIconById(name);
  if (!icon) return null;

  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
      style={style}
      dangerouslySetInnerHTML={{ __html: icon.elements.join("\n") }}
      {...props}
    />
  );
}

/**
 * Returns formatted standalone raw SVG code for a given icon.
 */
export function getRawSvg(
  icon: AppIconItemType,
  options?: {
    color?: string;
    strokeWidth?: number;
    size?: number;
    className?: string;
  }
): string {
  const color = options?.color || "currentColor";
  const strokeWidth = options?.strokeWidth || 1.75;
  const size = options?.size || 24;
  const cls = options?.className || `corex-app-icon corex-app-icon--${icon.id}`;

  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="${color}" stroke-width="${strokeWidth}" stroke-linecap="round" stroke-linejoin="round" class="${cls}">`,
    ...icon.elements.map((el) => `  ${el}`),
    "</svg>",
  ].join("\n");
}

/**
 * Returns a ready-to-use React JSX component snippet.
 */
export function getReactSnippet(icon: AppIconItemType): string {
  const componentName = icon.title
    .replace(/[^a-zA-Z0-9]/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("") + "Icon";

  const jsxElements = icon.elements
    .map((el) =>
      "    " +
      el
        .replace(/stroke-width/g, "strokeWidth")
        .replace(/stroke-linecap/g, "strokeLinecap")
        .replace(/stroke-linejoin/g, "strokeLinejoin")
        .replace(/stroke-dasharray/g, "strokeDasharray")
    )
    .join("\n");

  return `import * as React from "react";

export interface ${componentName}Props extends React.SVGProps<SVGSVGElement> {
  size?: number | string;
  color?: string;
  strokeWidth?: number;
}

export function ${componentName}({
  size = 24,
  color = "currentColor",
  strokeWidth = 1.75,
  className,
  ...props
}: ${componentName}Props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
      {...props}
    >
${jsxElements}
    </svg>
  );
}`;
}

/**
 * Returns a ready-to-use Shopify Liquid theme snippet.
 */
export function getLiquidSnippet(icon: AppIconItemType): string {
  const rawSvg = getRawSvg(icon, { size: 24 });
  return `{% comment %}
  Store Trust Badge: ${icon.title}
  File: snippets/icon-${icon.id}.liquid
{% endcomment %}
<span class="store-badge-icon store-badge-icon--${icon.id}" aria-hidden="true">
${rawSvg}
</span>`;
}

/**
 * Returns a CSS Data URI (data:image/svg+xml;utf8,...).
 */
export function getDataUri(icon: AppIconItemType, color = "#111827"): string {
  const svg = getRawSvg(icon, { color });
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}
