import type { ResourceItemType, ResourceTabItemType } from "./types";

export const DEFAULT_PAGE_SIZE = 5;

export const RESOURCE_TABS: ResourceTabItemType[] = [
  { id: "all", content: "All" },
  { id: "active", content: "Active" },
  { id: "draft", content: "Draft" },
  { id: "archived", content: "Archived" },
];

export const MOCK_RESOURCES: ResourceItemType[] = [
  {
    id: "prod-1",
    title: "Minimalist Merino Wool Sweater",
    sku: "WOL-SWT-001",
    vendor: "Nordic Loom",
    category: "Apparel",
    status: "active",
    inventory: 142,
    price: "$149.00",
    imageUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=100&h=100&fit=crop",
    updatedAt: "2 hours ago",
  },
  {
    id: "prod-2",
    title: "Handmade Ceramic Pour-Over Set",
    sku: "CER-PO-042",
    vendor: "Studio Terra",
    category: "Home & Kitchen",
    status: "active",
    inventory: 38,
    price: "$68.00",
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=100&h=100&fit=crop",
    updatedAt: "5 hours ago",
  },
  {
    id: "prod-3",
    title: "Full-Grain Leather Tote Bag",
    sku: "LEA-TOT-019",
    vendor: "Atelier Cuir",
    category: "Accessories",
    status: "active",
    inventory: 19,
    price: "$210.00",
    imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=100&h=100&fit=crop",
    updatedAt: "Yesterday",
  },
  {
    id: "prod-4",
    title: "Organic Linen Bedding Sheet Set",
    sku: "LIN-BED-104",
    vendor: "Nordic Loom",
    category: "Home & Kitchen",
    status: "draft",
    inventory: 0,
    price: "$185.00",
    imageUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=100&h=100&fit=crop",
    updatedAt: "2 days ago",
  },
  {
    id: "prod-5",
    title: "Cast Iron Dutch Oven 5.5 Qt",
    sku: "IRN-DO-005",
    vendor: "Forge & Fire",
    category: "Home & Kitchen",
    status: "active",
    inventory: 64,
    price: "$120.00",
    imageUrl: "https://images.unsplash.com/photo-1584990347449-3990f11d95be?w=100&h=100&fit=crop",
    updatedAt: "3 days ago",
  },
  {
    id: "prod-6",
    title: "Cold-Brew Coffee Maker Bottle",
    sku: "CBW-BOT-008",
    vendor: "Studio Terra",
    category: "Home & Kitchen",
    status: "archived",
    inventory: 0,
    price: "$45.00",
    imageUrl: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=100&h=100&fit=crop",
    updatedAt: "1 week ago",
  },
  {
    id: "prod-7",
    title: "Heavyweight Boxy Cotton Tee",
    sku: "COT-TEE-022",
    vendor: "Nordic Loom",
    category: "Apparel",
    status: "active",
    inventory: 310,
    price: "$48.00",
    imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=100&h=100&fit=crop",
    updatedAt: "1 week ago",
  },
  {
    id: "prod-8",
    title: "Titanium Mechanical Pen",
    sku: "TIT-PEN-001",
    vendor: "Forge & Fire",
    category: "Accessories",
    status: "draft",
    inventory: 15,
    price: "$85.00",
    imageUrl: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=100&h=100&fit=crop",
    updatedAt: "2 weeks ago",
  },
  {
    id: "prod-9",
    title: "Hand-Poured Soy Wax Candle",
    sku: "SOY-CND-012",
    vendor: "Studio Terra",
    category: "Home & Kitchen",
    status: "active",
    inventory: 88,
    price: "$32.00",
    imageUrl: "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=100&h=100&fit=crop",
    updatedAt: "2 weeks ago",
  },
  {
    id: "prod-10",
    title: "Recycled Wool Winter Scarf",
    sku: "WOL-SCF-003",
    vendor: "Nordic Loom",
    category: "Apparel",
    status: "archived",
    inventory: 4,
    price: "$65.00",
    imageUrl: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=100&h=100&fit=crop",
    updatedAt: "3 weeks ago",
  },
];

export const RESOURCE_CATEGORIES = [
  "All categories",
  "Apparel",
  "Home & Kitchen",
  "Accessories",
];
