#!/usr/bin/env node
/**
 * Regenerates src/version.ts from package.json.
 *
 * The "version" field in package.json is the single source of truth: it is what
 * npm publishes. This script copies it into the exported COREX_UI_VERSION
 * constant so the two can never disagree.
 *
 * Runs as part of `pnpm build` (and therefore before every publish). The
 * version test asserts the two agree, so a bump that forgets to regenerate
 * fails CI instead of shipping a version that never existed.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const packagePath = fileURLToPath(new URL("../package.json", import.meta.url));
const outputPath = fileURLToPath(new URL("../src/version.ts", import.meta.url));

const { version } = JSON.parse(readFileSync(packagePath, "utf-8"));

if (typeof version !== "string" || !/^\d+\.\d+\.\d+/.test(version)) {
  console.error(
    `[sync-version] package.json has no usable "version" field (got ${JSON.stringify(
      version,
    )})`,
  );
  process.exit(1);
}

const contents = `// AUTO-GENERATED by scripts/sync-version.mjs - do not edit by hand.
// Source of truth: the "version" field in package.json.
// Regenerate with \`pnpm sync:version\` (also runs as part of \`pnpm build\`).
export const COREX_UI_VERSION = "${version}";
export const version = COREX_UI_VERSION;
`;

let existing = null;
try {
  existing = readFileSync(outputPath, "utf-8");
} catch {
  existing = null;
}

if (existing === contents) {
  console.log(`[sync-version] src/version.ts already matches package.json (${version})`);
} else {
  writeFileSync(outputPath, contents);
  console.log(`[sync-version] wrote src/version.ts from package.json (${version})`);
}
