import type { AppCrossSellItemType, DiscountTierType } from "./types";

export const DEFAULT_DISCOUNT_TIERS: DiscountTierType[] = [
  {
    id: "tier-1",
    appsCount: 2,
    discountPercent: 10,
    label: "2 apps installed · 10% off",
  },
  {
    id: "tier-2",
    appsCount: 3,
    discountPercent: 20,
    label: "3 apps installed · 20% off",
  },
  {
    id: "tier-3",
    appsCount: 4,
    discountPercent: 30,
    label: "4+ apps installed · 30% off",
  },
];

export const DEFAULT_APPS_LIST: AppCrossSellItemType[] = [
  {
    id: "claimify",
    name: "Claimify RMA, Claims & Warranty",
    category: "Handle returns, exchanges, and warranty claims in one place",
    installed: false,
    iconBg: "linear-gradient(135deg, #0284c7 0%, #0369a1 100%)",
    iconType: "claimify",
    builtForShopify: true,
    rating: 5.0,
    reviewsCount: 6,
    pricingBadge: "Free trial available",
    appUrl: "https://apps.shopify.com/claimify",
    unlockDiscountText: "Install to unlock 10% off",
  },
  {
    id: "maestro-theme-scheduler",
    name: "Maestro Theme Scheduler",
    category: "Automate scheduling for sections, blocks, and theme publishing",
    installed: true,
    iconBg: "linear-gradient(135deg, #6366f1 0%, #4338ca 100%)",
    iconType: "theme-scheduler",
    builtForShopify: true,
    rating: 5.0,
    reviewsCount: 10,
    pricingBadge: "Free trial available",
    appUrl: "https://apps.shopify.com/maestro-theme-scheduler",
    unlockDiscountText: "Installed",
  },
  {
    id: "maestro-products-scheduler",
    name: "Maestro Products Scheduler",
    category: "Save time by scheduling and automating product updates",
    installed: false,
    iconBg: "linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%)",
    iconType: "products-scheduler",
    builtForShopify: true,
    rating: 5.0,
    reviewsCount: 5,
    pricingBadge: "Free trial available",
    appUrl: "https://apps.shopify.com/product-maestro-scheduler",
    unlockDiscountText: "Install to unlock 10% off",
  },
  {
    id: "giftcard-balance-checker",
    name: "Gift Card Checker By Maestro",
    category: "Reduce inquiries with self-service gift-card balance checks",
    installed: false,
    iconBg: "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
    iconType: "giftcard",
    rating: 5.0,
    reviewsCount: 4,
    pricingBadge: "Free trial available",
    appUrl: "https://apps.shopify.com/giftcard-balance-checker",
    unlockDiscountText: "Install to unlock 10% off",
  },
  {
    id: "floaty",
    name: "Floaty Icons & Social Buttons",
    category: "Floating social, contact, and custom icons for your store",
    installed: false,
    iconBg: "linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)",
    iconType: "floaty",
    pricingBadge: "Free plan available",
    appUrl: "https://apps.shopify.com/floaty",
    unlockDiscountText: "Install to unlock 10% off",
  },
  {
    id: "theme-visibility-scheduler",
    name: "Maestro Visibility Scheduler",
    category: "Avoid manual work by automating your sections visibility!",
    installed: false,
    iconBg: "linear-gradient(135deg, #ec4899 0%, #be185d 100%)",
    iconType: "visibility-scheduler",
    rating: 3.1,
    reviewsCount: 3,
    pricingBadge: "Free trial available",
    appUrl: "https://apps.shopify.com/theme-visibility-scheduler",
    unlockDiscountText: "Install to unlock 10% off",
  },
  {
    id: "workify",
    name: "Workify ‑ Job Offers & Hiring",
    category: "Hire faster by posting jobs and collecting applications on your store",
    installed: true,
    iconBg: "linear-gradient(135deg, #10b981 0%, #047857 100%)",
    iconType: "workify",
    rating: 5.0,
    reviewsCount: 1,
    pricingBadge: "Free trial available",
    appUrl: "https://apps.shopify.com/workify",
    unlockDiscountText: "Installed",
  },
  {
    id: "rank-smart-collections",
    name: "Rank Smart Collections",
    category: "Rankify - Create & Sort by what actually sells.",
    installed: false,
    iconBg: "linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)",
    iconType: "rankify",
    rating: 5.0,
    reviewsCount: 2,
    pricingBadge: "Free trial available",
    appUrl: "https://apps.shopify.com/rankify-smart-collection-sort",
    unlockDiscountText: "Install to unlock 10% off",
  },
  {
    id: "maestro-collections-scheduler",
    name: "Maestro Collections Scheduler",
    category: "Save time by scheduling and automating collections changes.",
    installed: false,
    iconBg: "linear-gradient(135deg, #a855f7 0%, #7e22ce 100%)",
    iconType: "collections-scheduler",
    pricingBadge: "Free plan available",
    appUrl: "https://apps.shopify.com/maestro-collections-schedule",
    unlockDiscountText: "Install to unlock 10% off",
  },
  {
    id: "orda",
    name: "ORDA ‑ Order Tracker",
    category: "Branded Tracking Pages. Fewer Support Tickets.",
    installed: false,
    iconBg: "linear-gradient(135deg, #f97316 0%, #c2410c 100%)",
    iconType: "orda",
    pricingBadge: "Free",
    appUrl: "https://apps.shopify.com/order-helper-dev",
    unlockDiscountText: "Install to unlock 10% off",
  },
  {
    id: "cartify",
    name: "Cartify ‑ Multi Carts Sharing",
    category: "Allow customer to shop in multi-cart and share their carts",
    installed: false,
    iconBg: "linear-gradient(135deg, #14b8a6 0%, #0f766e 100%)",
    iconType: "cartify",
    pricingBadge: "Free",
    appUrl: "https://apps.shopify.com/cartify-multi-carts-sharing",
    unlockDiscountText: "Install to unlock 10% off",
  },
  {
    id: "quick-notice",
    name: "Quick Notice ‑ Announcements",
    category: "Create Clear alerts to Keep customers informed and unconfused.",
    installed: false,
    iconBg: "linear-gradient(135deg, #ef4444 0%, #b91c1c 100%)",
    iconType: "quick-notice",
    pricingBadge: "Free plan available",
    appUrl: "https://apps.shopify.com/quick-notice-clear-alert",
    unlockDiscountText: "Install to unlock 10% off",
  },
  {
    id: "matchly",
    name: "Matchly ‑ Quiz & Forms Builder",
    category: "Recommend products and capture leads with quizzes and forms",
    installed: false,
    iconBg: "linear-gradient(135deg, #eab308 0%, #a16207 100%)",
    iconType: "matchly",
    pricingBadge: "Free trial available",
    appUrl: "https://apps.shopify.com/matchly-1",
    unlockDiscountText: "Install to unlock 10% off",
  },
  {
    id: "prizify",
    name: "Prizify ‑ Loyalty & Rewards",
    category: "Enhance Repeat purchases with a custom loyalty program",
    installed: true,
    iconBg: "linear-gradient(135deg, #f43f5e 0%, #be123c 100%)",
    iconType: "prizify",
    pricingBadge: "Free plan available",
    appUrl: "https://apps.shopify.com/prizify-loyalty-rewards",
    unlockDiscountText: "Installed",
  },
  {
    id: "subflow",
    name: "SubFlow ‑ Subscriptions & Save",
    category: "Manage subscriptions with automated billing",
    installed: false,
    iconBg: "linear-gradient(135deg, #84cc16 0%, #4d7c0f 100%)",
    iconType: "subflow",
    pricingBadge: "Free",
    appUrl: "https://apps.shopify.com/subscriptions-5",
    unlockDiscountText: "Install to unlock 10% off",
  },
];
