// AUTO-GENERATED by scripts/sync-version.mjs - do not edit by hand.
// Source of truth: the "version" field in package.json.
// Regenerate with `pnpm sync:version` (also runs as part of `pnpm build`).
export const COREX_UI_VERSION = "2.1.5";
export const version = COREX_UI_VERSION;
