import type { CSSProperties } from "react";
import type {
  BrandColorsType,
  CartPresetIdType,
  CartPresetStyleType,
  FlowStageType,
} from "./types";

export const ACCENT = "#008060";
export const ACCENT_SOFT = "#E3F1EC";
export const BG = "#F6F6F7";
export const CARD = "#FFFFFF";
export const BORDER = "#E3E3E3";
export const BORDER_STRONG = "#C9CCCF";
export const TEXT = "#1A1A1A";
export const TEXT_SECONDARY = "#9A9A9A";
export const RADIUS = 8;
export const SHADOW = "0 2px 4px rgba(0,0,0,.04), 0 14px 34px rgba(0,0,0,.07)";
export const FONT = "'Inter', -apple-system, BlinkMacSystemFont, sans-serif";

export const DEFAULT_BRAND_COLORS: BrandColorsType = {
  primary: "#008060",
  secondary: "#1A1A1A",
  accent: "#E8B84B",
  background: "#F6F6F7",
  source: "default",
};

export const CART_PRESET_STYLES: Record<CartPresetIdType, CartPresetStyleType> = {
  minimal: {
    container: {},
    header: { borderBottom: `1px solid ${BORDER}`, paddingBottom: 6 },
    title: {},
    item: {},
    thumb: { borderRadius: 3 },
    price: {},
    qty: {},
    cta: { background: "#fff", color: TEXT, border: `1.4px solid ${TEXT}` },
  },
  bold: {
    container: {},
    header: { background: TEXT, margin: "-10px -10px 6px", padding: "9px 10px" },
    title: { color: "#fff" },
    item: {},
    thumb: {},
    price: { color: ACCENT, fontWeight: 800 },
    qty: {},
    cta: { background: ACCENT },
  },
  rounded: {
    container: { borderRadius: 16 },
    header: {},
    title: {},
    item: {
      background: "#FAFAFA",
      borderRadius: 10,
      padding: "5px 6px",
      margin: "0 -2px",
    },
    thumb: { borderRadius: 7 },
    price: {},
    qty: { borderRadius: 99, padding: "1px 6px" },
    cta: { borderRadius: 99, background: ACCENT },
  },
  editorial: {
    container: {},
    header: { borderBottom: `1.4px solid ${TEXT}`, paddingBottom: 6 },
    title: { fontStyle: "italic" },
    item: { borderBottom: `1px dashed ${BORDER}`, paddingBottom: 6 },
    thumb: { borderRadius: 0 },
    price: { fontStyle: "italic" },
    qty: {},
    cta: {
      background: "#fff",
      color: TEXT,
      border: `1.4px solid ${TEXT}`,
      borderRadius: 0,
    },
  },
};

export const FLOW: FlowStageType[] = [
  {
    type: "processing",
    texts: ["Initializing your workspace...", "Getting things ready..."],
  },
  {
    type: "questions",
    kind: "choice",
    title: "Tell us about your store",
    questions: [
      {
        id: "volume",
        type: "single",
        question: "What's your average monthly order volume?",
        subtitle: "This helps us tailor performance settings to your store size.",
        options: [
          "Under 100 orders",
          "100–500 orders",
          "500–2,000 orders",
          "2,000+ orders",
        ],
      },
    ],
  },
  {
    type: "processing",
    texts: ["Validate your preferences...", "Analyzing your store data..."],
  },
  {
    type: "questions",
    kind: "toggle-grid",
    id: "addons",
    title: "Add revenue tools to your cart",
    subtitle: "Turn these on now, or add them anytime from your dashboard.",
    options: [
      {
        id: "shipping-protection",
        icon: "📦",
        title: "Shipping protection",
        desc: "Let customers insure their order against loss or damage.",
        default: false,
      },
      {
        id: "warranty",
        icon: "🛡️",
        title: "Product warranty",
        desc: "Offer extended warranty coverage at checkout.",
        default: false,
      },
      {
        id: "gift-wrap",
        icon: "🎁",
        title: "Gift wrapping",
        desc: "Let customers add gift wrap for a small fee.",
        default: false,
      },
      {
        id: "cart-upsells",
        icon: "🛒",
        title: "Cart drawer upsells",
        desc: "Show smart product recommendations in the cart.",
        default: true,
        badge: "Recommended for Journeva",
      },
    ],
  },
  {
    type: "processing",
    texts: ["Configuring your revenue tools...", "Applying your preferences..."],
  },
  {
    type: "questions",
    kind: "style-preset",
    id: "cartStyle",
    title: "Pick a cart drawer style",
    subtitle:
      "A live preview of how your cart drawer will look — you can fine-tune it later.",
    default: "minimal",
    options: [
      { id: "minimal", label: "Minimal" },
      { id: "bold", label: "Bold" },
      { id: "rounded", label: "Rounded" },
      { id: "editorial", label: "Editorial" },
    ],
  },
  {
    type: "processing",
    texts: ["Initializing your cart branding...", "Personalizing your storefront..."],
  },
  {
    type: "questions",
    kind: "brand-color",
    id: "brand",
    title: "Add your brand colors",
    subtitle: "We'll use these across your cart and upsell widgets.",
  },
  { type: "processing", texts: ["Finalizing your setup...", "Wrapping up..."] },
  { type: "complete" },
];

export const styles: Record<string, CSSProperties | ((...args: any[]) => CSSProperties)> =
  {
    page: {},
    bgGrid: {
      position: "fixed",
      inset: 0,
      pointerEvents: "none",
      zIndex: 0,
      backgroundImage: "radial-gradient(rgba(0,0,0,0.035) 1px, transparent 1px)",
      backgroundSize: "26px 26px",
      WebkitMaskImage: "radial-gradient(circle at 50% 25%, black, transparent 68%)",
      maskImage: "radial-gradient(circle at 50% 25%, black, transparent 68%)",
    },
    progressPill: {
      position: "fixed",
      top: 20,
      left: "50%",
      background: "#fff",
      border: `1px solid ${BORDER}`,
      borderRadius: 999,
      boxShadow: SHADOW,
      padding: "10px 18px",
      display: "flex",
      alignItems: "center",
      gap: 12,
      zIndex: 20,
      maxWidth: "92vw",
      transition: "opacity .3s ease, transform .3s ease",
    },
    progressTrack: {
      width: 90,
      height: 4,
      background: BORDER,
      borderRadius: 99,
      overflow: "hidden",
      flexShrink: 0,
    },
    progressFill: {
      height: "100%",
      background: ACCENT,
      borderRadius: 99,
      transition: "width .5s cubic-bezier(.22,1,.36,1)",
    },
    progressLabel: {
      fontSize: ".78rem",
      fontWeight: 600,
      color: TEXT_SECONDARY,
      whiteSpace: "nowrap",
    },

    stageWrap: {
      width: "100%",
      maxWidth: 500,
      position: "relative",
      zIndex: 1,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },

    processing: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 16,
      padding: "50px 20px",
      textAlign: "center",
      width: "100%",
    },
    spinner: {
      width: 24,
      height: 24,
      borderRadius: "50%",
      border: `3px solid ${BORDER}`,
      borderTopColor: ACCENT,
      animation: "spin .75s linear infinite",
      flexShrink: 0,
    },
    processingText: {
      backgroundImage: `linear-gradient(90deg, ${TEXT_SECONDARY} 0%, ${TEXT} 22%, ${TEXT} 62%, ${TEXT_SECONDARY} 84%)`,
      backgroundSize: "260% 100%",
      WebkitBackgroundClip: "text",
      backgroundClip: "text",
      WebkitTextFillColor: "transparent",
      color: "transparent",
      animation: "shimmer 2.4s linear infinite",
      transition: "opacity .3s ease, transform .3s ease",
    },

    panel: {
      background: CARD,
      border: `1px solid ${BORDER}`,
      borderRadius: 14,
      boxShadow: SHADOW,
      maxWidth: 500,
      width: "100%",
      marginBottom: 16,
      boxSizing: "border-box",
    },
    batchTitle: { fontSize: "1.15rem", fontWeight: 700, marginBottom: 6, color: TEXT },
    batchSubtitle: {
      fontSize: ".85rem",
      color: TEXT_SECONDARY,
      margin: "0 0 20px",
      lineHeight: 1.5,
    },

    btn: {
      width: "100%",
      maxWidth: 500,
      padding: "13px 20px",
      borderRadius: RADIUS,
      border: "none",
      background: ACCENT,
      color: "#fff",
      fontWeight: 600,
      fontSize: ".95rem",
      cursor: "pointer",
      transition: "background .15s ease, transform .1s ease, box-shadow .15s ease",
    },
    btnDisabled: { background: BORDER, color: TEXT_SECONDARY, cursor: "not-allowed" },

    questionBlock: { marginBottom: 24 },
    qTitle: { fontSize: ".95rem", fontWeight: 600, marginBottom: 4, color: TEXT },
    qSub: {
      fontSize: ".83rem",
      color: TEXT_SECONDARY,
      marginBottom: 12,
      lineHeight: 1.45,
    },
    qOptions: { display: "flex", flexDirection: "column", gap: 8 },
    qOption: {
      display: "flex",
      alignItems: "center",
      gap: 12,
      border: `1px solid ${BORDER}`,
      borderRadius: RADIUS,
      padding: "12px 14px",
      background: "#fff",
      cursor: "pointer",
      textAlign: "left",
      fontSize: ".92rem",
      color: TEXT,
      width: "100%",
      fontFamily: "inherit",
      transition: "border-color .15s ease, background .15s ease",
    },
    qOptionSelected: { borderColor: ACCENT, background: ACCENT_SOFT },
    indicator: {
      width: 18,
      height: 18,
      borderRadius: "50%",
      flexShrink: 0,
      border: `2px solid ${BORDER_STRONG}`,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      transition: "border-color .15s ease, background .15s ease",
    },
    indicatorSquare: { borderRadius: 5 },
    indicatorSelected: { borderColor: ACCENT, background: ACCENT },
    checkIcon: {
      width: 10,
      height: 10,
      transition: "opacity .15s ease, transform .15s ease",
    },
    checkPath: {
      fill: "none",
      stroke: "#fff",
      strokeWidth: 2.6,
      strokeLinecap: "round",
      strokeLinejoin: "round",
    },
    optLabel: { flex: 1 },
    qInputWrap: { display: "flex", alignItems: "center", gap: 8 },
    qInputPrefix: {
      fontSize: ".95rem",
      color: TEXT_SECONDARY,
      border: `1px solid ${BORDER}`,
      borderRight: "none",
      borderRadius: `${RADIUS}px 0 0 ${RADIUS}px`,
      padding: "10px 10px 10px 12px",
      background: "#FAFAFA",
    },
    qInput: {
      fontFamily: FONT,
      fontSize: ".95rem",
      color: TEXT,
      border: `1px solid ${BORDER}`,
      borderLeft: "none",
      borderRadius: `0 ${RADIUS}px ${RADIUS}px 0`,
      padding: "10px 12px",
      width: "100%",
      background: "#fff",
      boxSizing: "border-box",
    },

    toggleGrid: { display: "grid", gap: 12 },
    toggleCard: {
      border: `1px solid ${BORDER}`,
      borderRadius: 12,
      padding: 16,
      display: "flex",
      flexDirection: "column",
      gap: 8,
      position: "relative",
      cursor: "pointer",
      background: "#fff",
      transition: "border-color .15s ease, background .15s ease",
    },
    toggleCardOn: { borderColor: ACCENT, background: ACCENT_SOFT },
    badge: {
      position: "absolute",
      top: 10,
      right: 10,
      background: ACCENT,
      color: "#fff",
      fontSize: ".6rem",
      fontWeight: 700,
      padding: "3px 8px",
      borderRadius: 99,
      letterSpacing: ".01em",
      maxWidth: 112,
      lineHeight: 1.3,
      textAlign: "right",
    },
    toggleIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 10,
      background: ACCENT_SOFT,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "1.1rem",
    },
    toggleIconWrapOn: { background: "#fff" },
    toggleTitle: { fontSize: ".92rem", fontWeight: 700, color: TEXT, paddingRight: 56 },
    toggleDesc: { fontSize: ".78rem", color: TEXT_SECONDARY, lineHeight: 1.4, flex: 1 },
    toggleSwitch: {
      alignSelf: "flex-end",
      width: 36,
      height: 20,
      borderRadius: 99,
      background: BORDER_STRONG,
      position: "relative",
      transition: "background .15s ease",
      marginTop: 2,
    },
    toggleSwitchOn: { background: ACCENT },
    hintNote: {
      fontSize: ".78rem",
      color: TEXT_SECONDARY,
      margin: "14px 0 0",
      textAlign: "center",
      lineHeight: 1.4,
    },

    presetGrid: { display: "grid", gap: 12 },
    presetCard: {
      border: `1px solid ${BORDER}`,
      borderRadius: 12,
      padding: 10,
      cursor: "pointer",
      textAlign: "center",
      transition: "border-color .15s ease, background .15s ease",
    },
    presetCardSelected: { borderColor: ACCENT, background: ACCENT_SOFT },
    presetLabel: { fontSize: ".8rem", fontWeight: 600, color: TEXT, marginTop: 8 },

    cartPreview: {
      border: `1px solid ${BORDER}`,
      background: "#fff",
      borderRadius: 8,
      overflow: "hidden",
      display: "flex",
      flexDirection: "column",
      padding: 10,
      gap: 6,
      height: 176,
      textAlign: "left",
      boxSizing: "border-box",
    },
    cpHeader: { display: "flex", alignItems: "center", justifyContent: "space-between" },
    cpTitle: { fontSize: ".7rem", fontWeight: 700, color: TEXT },
    cpClose: { fontSize: ".75rem", color: TEXT_SECONDARY, lineHeight: 1 },
    cpItem: { display: "flex", alignItems: "center", gap: 7 },
    cpThumb: {
      width: 24,
      height: 24,
      borderRadius: 4,
      background: "linear-gradient(135deg,#DADCDD,#EFEFEF)",
      flexShrink: 0,
    },
    cpInfo: { flex: 1, display: "flex", flexDirection: "column", gap: 3, minWidth: 0 },
    cpName: { height: 5, width: "75%", borderRadius: 2, background: "#DADCDD" },
    cpVariant: { height: 4, width: "48%", borderRadius: 2, background: "#EDEDED" },
    cpRight: {
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-end",
      gap: 3,
      flexShrink: 0,
    },
    cpPrice: { fontSize: ".66rem", fontWeight: 700, color: TEXT },
    cpQty: {
      display: "flex",
      alignItems: "center",
      gap: 2,
      fontSize: ".52rem",
      color: TEXT_SECONDARY,
      border: `1px solid ${BORDER}`,
      borderRadius: 4,
      padding: "1px 4px",
    },
    cpFooter: { marginTop: "auto", display: "flex", flexDirection: "column", gap: 6 },
    cpSubtotal: {
      display: "flex",
      justifyContent: "space-between",
      fontSize: ".68rem",
      fontWeight: 700,
      color: TEXT,
    },
    cpCta: {
      textAlign: "center",
      fontSize: ".68rem",
      fontWeight: 700,
      padding: 7,
      borderRadius: 6,
      background: TEXT,
      color: "#fff",
    },

    scanCard: {
      display: "flex",
      alignItems: "center",
      gap: 14,
      padding: 16,
      borderRadius: 12,
      background: `linear-gradient(135deg, ${ACCENT_SOFT}, #fff 65%)`,
      border: `1px solid ${BORDER}`,
      marginBottom: 22,
    },
    scanVisual: {
      position: "relative",
      width: 44,
      height: 44,
      flexShrink: 0,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    scanOrbit: {
      position: "absolute",
      inset: 0,
      borderRadius: "50%",
      border: `2px solid ${ACCENT}`,
      opacity: 0.35,
      animation: "scanPulse 1.8s ease-out infinite",
    },
    scanStoreIcon: { width: 20, height: 20, position: "relative", zIndex: 1 },
    scanCopy: { flex: 1, minWidth: 0 },
    scanTitle: { fontSize: ".9rem", fontWeight: 700, color: TEXT, marginBottom: 2 },
    scanDesc: { fontSize: ".76rem", color: TEXT_SECONDARY, lineHeight: 1.4 },
    scanCta: {
      padding: "9px 16px",
      borderRadius: 8,
      border: "none",
      background: ACCENT,
      color: "#fff",
      fontWeight: 600,
      fontSize: ".82rem",
      cursor: "pointer",
      whiteSpace: "nowrap",
      flexShrink: 0,
      display: "flex",
      alignItems: "center",
      gap: 7,
      transition: "background .15s ease, transform .1s ease",
    },
    miniSpinner: {
      width: 12,
      height: 12,
      borderRadius: "50%",
      border: "2px solid rgba(255,255,255,.4)",
      borderTopColor: "#fff",
      animation: "spin .7s linear infinite",
    },
    scanStatus: {
      display: "flex",
      alignItems: "center",
      gap: 6,
      fontSize: ".78rem",
      color: ACCENT,
      fontWeight: 600,
      margin: "-10px 0 18px",
      opacity: 0,
      transform: "translateY(-4px)",
      transition: "opacity .35s ease, transform .35s ease",
    },
    scanStatusVisible: { opacity: 1, transform: "translateY(0)" },

    brandSwatches: { display: "flex", gap: 10, marginBottom: 20 },
    swatchCard: { flex: 1, minWidth: 0, textAlign: "center" },
    swatchColor: (bg: string): CSSProperties => ({
      position: "relative",
      width: "100%",
      aspectRatio: "1 / 1",
      borderRadius: 11,
      cursor: "pointer",
      boxShadow: `0 0 0 1px ${BORDER}`,
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "flex-end",
      overflow: "hidden",
      background: bg,
      transition: "transform .15s ease, box-shadow .15s ease",
    }),
    colorInput: {
      position: "absolute",
      inset: 0,
      width: "160%",
      height: "160%",
      left: "-30%",
      top: "-30%",
      opacity: 0,
      cursor: "pointer",
      border: "none",
    },
    swatchEdit: {
      position: "relative",
      zIndex: 1,
      margin: 4,
      width: 16,
      height: 16,
      borderRadius: "50%",
      background: "rgba(255,255,255,.9)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: ".6rem",
      pointerEvents: "none",
    },
    swatchLabel: {
      display: "block",
      fontSize: ".68rem",
      color: TEXT_SECONDARY,
      marginTop: 6,
    },
    swatchHex: {
      display: "block",
      fontSize: ".7rem",
      fontWeight: 700,
      color: TEXT,
      fontFamily: "'SF Mono', Menlo, monospace",
    },

    brandPreview: (bg: string): CSSProperties => ({
      border: `1px solid ${BORDER}`,
      borderRadius: 12,
      padding: 16,
      background: bg,
      transition: "background .3s ease",
    }),
    previewCaption: {
      fontSize: ".75rem",
      color: TEXT_SECONDARY,
      fontWeight: 600,
      marginBottom: 10,
      display: "block",
    },
    previewChipRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
    previewBtn: (bg: string): CSSProperties => ({
      padding: "9px 18px",
      borderRadius: 8,
      border: "none",
      fontWeight: 700,
      fontSize: ".82rem",
      color: "#fff",
      background: bg,
      transition: "background .3s ease",
    }),
    previewBadge: (bg: string): CSSProperties => ({
      padding: "4px 10px",
      borderRadius: 99,
      fontSize: ".72rem",
      fontWeight: 700,
      color: "#fff",
      background: bg,
      transition: "background .3s ease",
    }),

    complete: { textAlign: "center", padding: "8px 0" },
    checkWrap: { display: "flex", justifyContent: "center", marginBottom: 18 },
    checkCircle: {
      width: 56,
      height: 56,
      borderRadius: "50%",
      background: ACCENT_SOFT,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    checkSvg: { width: 26, height: 26 },
    checkPathComplete: {
      fill: "none",
      stroke: ACCENT,
      strokeWidth: 3,
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeDasharray: 24,
    },
    completeH2: { fontSize: "1.3rem", fontWeight: 700, marginBottom: 6 },
    completeP: { fontSize: ".9rem", color: TEXT_SECONDARY, margin: 0 },
  };
