import type { ActivityItemType } from "./types";

export const FILTER_OPTIONS: { label: string; value: ActivityItemType["eventType"] }[] = [
  { label: "All activities", value: "all" },
  { label: "Orders", value: "order" },
  { label: "Payments", value: "payment" },
  { label: "Inventory", value: "inventory" },
  { label: "Customer messages", value: "message" },
  { label: "Fulfillment & Shipping", value: "fulfillment" },
];

export const MOCK_ACTIVITIES: ActivityItemType[] = [
  {
    id: "act-1",
    title: "Order #1234 created",
    badgeText: "New Order",
    badgeTone: "info",
    timestamp: "2 minutes ago",
    dateGroup: "Today",
    description: "Customer John Doe placed a new order for $129.99",
    icon: "order",
    iconTone: "info",
    eventType: "order",
    details: [
      { label: "Order Id:", value: "#1234" },
      { label: "Amount:", value: "$129.99" },
      { label: "Customer:", value: "John Doe" },
    ],
    actions: [
      { label: "View order", variant: "secondary" },
      { label: "Contact customer", variant: "secondary" },
    ],
    payload: {
      orderId: "#1234",
      amount: 129.99,
      customer: "John Doe",
      email: "john.doe@example.com",
      lineItems: 2,
    },
  },
  {
    id: "act-2",
    title: "Payment received",
    badgeText: "Payment",
    badgeTone: "success",
    timestamp: "5 minutes ago",
    dateGroup: "Today",
    description: "Payment of $129.99 successfully processed via Stripe",
    icon: "payment",
    iconTone: "success",
    eventType: "payment",
    details: [
      { label: "Payment Method:", value: "Visa •••• 4242" },
      { label: "Transaction Id:", value: "tx_1a2b3c" },
    ],
    payload: {
      transactionId: "tx_1a2b3c",
      gateway: "Stripe",
      amount: 129.99,
      currency: "USD",
      cardLast4: "4242",
      status: "succeeded",
    },
  },
  {
    id: "act-3",
    title: "Low inventory alert",
    badgeText: "Inventory",
    badgeTone: "warning",
    timestamp: "1 hour ago",
    dateGroup: "Today",
    description: 'Product "Premium T-Shirt" is running low on stock',
    icon: "inventory",
    iconTone: "warning",
    eventType: "inventory",
    details: [
      { label: "Product:", value: "Premium T-Shirt" },
      { label: "Current Stock:", value: "3 units" },
      { label: "Threshold:", value: "5 units" },
    ],
    actions: [
      { label: "Restock", variant: "secondary" },
      { label: "View product", variant: "secondary" },
    ],
    payload: {
      sku: "TSHIRT-PREM-BLK-M",
      productName: "Premium T-Shirt",
      stock: 3,
      threshold: 5,
      warehouse: "Primary Facility",
    },
  },
  {
    id: "act-4",
    title: "Customer inquiry",
    badgeText: "Message",
    badgeTone: "info",
    timestamp: "3 hours ago",
    dateGroup: "Today",
    description: "Sarah Wilson sent a message about order #1230",
    icon: "chat",
    iconTone: "info",
    eventType: "message",
    details: [
      { label: "Customer:", value: "Sarah Wilson" },
      { label: "Subject:", value: "Order status inquiry" },
      { label: "Priority:", value: "Normal" },
    ],
    actions: [
      { label: "Reply", variant: "secondary" },
      { label: "View conversation", variant: "secondary" },
    ],
    payload: {
      ticketId: "TCK-8921",
      customer: "Sarah Wilson",
      email: "sarah.w@example.com",
      relatedOrder: "#1230",
      channel: "Email",
    },
  },
  {
    id: "act-5",
    title: "Order #1230 shipped",
    badgeText: "Shipped",
    badgeTone: "success",
    timestamp: "6 hours ago",
    dateGroup: "Today",
    description: "Package dispatched via FedEx with tracking number",
    icon: "order-fulfilled",
    iconTone: "success",
    eventType: "fulfillment",
    details: [
      { label: "Carrier:", value: "FedEx" },
      { label: "Tracking Number:", value: "FX-982341239" },
      { label: "Destination:", value: "New York, NY, USA" },
    ],
    actions: [
      { label: "Track package", variant: "secondary" },
      { label: "View order", variant: "secondary" },
    ],
    payload: {
      orderId: "#1230",
      carrier: "FedEx",
      trackingNumber: "FX-982341239",
      destination: "New York, NY, USA",
      estimatedDelivery: "Sep 16, 2026",
    },
  },
  {
    id: "act-6",
    title: "Discount campaign applied",
    badgeText: "Promotion",
    badgeTone: "info",
    timestamp: "Yesterday at 4:15 PM",
    dateGroup: "Yesterday",
    description: "Coupon code SUMMER25 redeemed for 25% off order #1228",
    icon: "order",
    iconTone: "info",
    eventType: "order",
    details: [
      { label: "Code:", value: "SUMMER25" },
      { label: "Discount Value:", value: "-$32.50" },
      { label: "Applied Order:", value: "#1228" },
    ],
    actions: [{ label: "View order", variant: "secondary" }],
    payload: {
      code: "SUMMER25",
      discount: 32.5,
      orderId: "#1228",
    },
  },
];
