import type { IntegrationItemType, WebhookLogItemType } from "./types";

export const MOCK_INTEGRATIONS: IntegrationItemType[] = [
  {
    id: "klaviyo",
    name: "Klaviyo",
    description: "Sync cart abandonments, profiles, and custom customer events to email flows.",
    category: "marketing",
    status: "connected",
    syncEnabled: true,
    iconTone: "success",
    lastSyncedAt: "3 mins ago",
    apiKey: "pk_live_8f3d9b1a0e",
  },
  {
    id: "gorgias",
    name: "Gorgias",
    description: "Display live customer cart contents directly inside agent support tickets.",
    category: "support",
    status: "connected",
    syncEnabled: true,
    iconTone: "info",
    lastSyncedAt: "10 mins ago",
    apiKey: "gor_sec_7a2b4c",
  },
  {
    id: "ga4",
    name: "Google Analytics 4",
    description: "Transmit client-side cart drawer engagement and add-to-cart events directly to GA4.",
    category: "analytics",
    status: "connected",
    syncEnabled: false,
    iconTone: "caution",
    lastSyncedAt: "Yesterday",
    apiKey: "G-89420BXYZ",
  },
  {
    id: "meta",
    name: "Meta Pixel & CAPI",
    description: "Server-side Conversions API integration for high-accuracy conversion tracking.",
    category: "marketing",
    status: "disconnected",
    syncEnabled: false,
    iconTone: "neutral",
  },
  {
    id: "slack",
    name: "Slack Notifications",
    description: "Send instant notifications to a designated channel whenever a high-value order completes.",
    category: "support",
    status: "disconnected",
    syncEnabled: false,
    iconTone: "neutral",
  },
  {
    id: "custom-webhook",
    name: "Custom Outbound Webhook",
    description: "Trigger raw HTTP POST payloads to your external ERP, warehouse, or Zapier endpoint.",
    category: "webhooks",
    status: "connected",
    syncEnabled: true,
    iconTone: "info",
    lastSyncedAt: "1 hour ago",
    webhookUrl: "https://api.merchant-systems.com/webhooks/orders",
  },
];

export const MOCK_WEBHOOK_LOGS: WebhookLogItemType[] = [
  {
    id: "log-1",
    topic: "cart/abandoned",
    status: "success",
    statusCode: 200,
    timestamp: "2 mins ago",
    durationMs: 142,
  },
  {
    id: "log-2",
    topic: "addon/added",
    status: "success",
    statusCode: 200,
    timestamp: "12 mins ago",
    durationMs: 88,
  },
  {
    id: "log-3",
    topic: "cart/checkout_started",
    status: "failed",
    statusCode: 504,
    timestamp: "35 mins ago",
    durationMs: 4200,
  },
  {
    id: "log-4",
    topic: "offer/redeemed",
    status: "success",
    statusCode: 200,
    timestamp: "1 hour ago",
    durationMs: 110,
  },
];
